"""Données à synchroniser sur Render au démarrage (création si absent)."""

SEED_USERS = [
    {
        'username': 'admin',
        'email': 'admin@vendoor.com',
        'password': 'admin123',
        'phone': '227',
        'role': 'admin',
    },
    {
        'username': 'vendoor_test',
        'email': 'test@vendoor.com',
        'password': '123456',
        'phone': '',
        'role': 'user',
    },
    {
        'username': 'iii',
        'email': 'iii@g',
        'password': 'iii123456',
        'phone': '12',
        'role': 'user',
    },
    {
        'username': 'iiii',
        'email': 'ii@g',
        'password': 'ii123456',
        'phone': '',
        'role': 'user',
    },
]

SEED_POSTS = [
    {
        'user_email': 'ii@g',
        'title': 'Air force color white',
        'description': 'white sneakers (Air force), brand new with a very resistant semelle.',
        'price': 500.0,
        'category': 'Clothing',
        'type': 'article',
        'image': 'images/808b658425ee46949e103000e158ad71.jfif',
        'promo': 50.0,
        'delivery_method': 'pickup',
        'pickup_location': 'common wealth',
    },
    {
        'user_email': 'ii@g',
        'title': 'bagpack black color',
        'description': 'new stock of black bagpacks with high quality texture and resistant to humidity',
        'price': 350.0,
        'category': 'Accessories',
        'type': 'article',
        'image': 'images/a80426e3549d4ced837d42fb27b83c9e.jfif',
        'promo': 15.0,
        'delivery_method': 'delivery',
        'pickup_location': '',
    },
    {
        'user_email': 'admin@vendoor.com',
        'title': 'handbag ',
        'description': 'stylish handbag for women with high value, because your appearance matters',
        'price': 600.0,
        'category': 'Accessories',
        'type': 'article',
        'image': 'images/4f926e94c9a842d4b764c4b9ebb04759.jfif',
        'promo': 10.0,
        'delivery_method': 'pickup',
        'pickup_location': 'Mensah sarbah',
    },
    {
        'user_email': 'ii@g',
        'title': 'Annonce iiii 1',
        'description': "Description de l'annonce 1 créée pour le compte iiii.",
        'price': 9842.04,
        'category': 'Service',
        'type': 'article',
        'image': 'https://placehold.co/600x400?text=Item+1',
        'promo': 0,
        'delivery_method': 'delivery',
        'pickup_location': '',
    },
    {
        'user_email': 'ii@g',
        'title': 'Annonce iiii 2',
        'description': "Description de l'annonce 2 créée pour le compte iiii.",
        'price': 2371.88,
        'category': 'Service',
        'type': 'service',
        'image': 'https://placehold.co/600x400?text=Item+2',
        'promo': 0,
        'delivery_method': 'pickup',
        'pickup_location': 'Campus central',
    },
    {
        'user_email': 'ii@g',
        'title': 'Annonce iiii 3',
        'description': "Description de l'annonce 3 créée pour le compte iiii.",
        'price': 1915.6,
        'category': 'Other',
        'type': 'article',
        'image': 'https://placehold.co/600x400?text=Item+3',
        'promo': 10.0,
        'delivery_method': 'delivery',
        'pickup_location': '',
    },
    {
        'user_email': 'ii@g',
        'title': 'Annonce iiii 4',
        'description': "Description de l'annonce 4 créée pour le compte iiii.",
        'price': 6166.23,
        'category': 'Clothing',
        'type': 'service',
        'image': 'https://placehold.co/600x400?text=Item+4',
        'promo': 0,
        'delivery_method': 'pickup',
        'pickup_location': 'Campus central',
    },
    {
        'user_email': 'ii@g',
        'title': 'Annonce iiii 5',
        'description': "Description de l'annonce 5 créée pour le compte iiii.",
        'price': 2608.54,
        'category': 'Service',
        'type': 'article',
        'image': 'https://placehold.co/600x400?text=Item+5',
        'promo': 0,
        'delivery_method': 'delivery',
        'pickup_location': '',
    },
    {
        'user_email': 'ii@g',
        'title': 'Annonce iiii 6',
        'description': "Description de l'annonce 6 créée pour le compte iiii.",
        'price': 8356.08,
        'category': 'Furniture',
        'type': 'service',
        'image': 'https://placehold.co/600x400?text=Item+6',
        'promo': 10.0,
        'delivery_method': 'pickup',
        'pickup_location': 'Campus central',
    },
    {
        'user_email': 'ii@g',
        'title': 'Annonce iiii 7',
        'description': "Description de l'annonce 7 créée pour le compte iiii.",
        'price': 7983.32,
        'category': 'Other',
        'type': 'article',
        'image': 'https://placehold.co/600x400?text=Item+7',
        'promo': 0,
        'delivery_method': 'delivery',
        'pickup_location': '',
    },
    {
        'user_email': 'ii@g',
        'title': 'Annonce iiii 8',
        'description': "Description de l'annonce 8 créée pour le compte iiii.",
        'price': 1442.65,
        'category': 'Other',
        'type': 'service',
        'image': 'https://placehold.co/600x400?text=Item+8',
        'promo': 0,
        'delivery_method': 'pickup',
        'pickup_location': 'Campus central',
    },
    {
        'user_email': 'ii@g',
        'title': 'Annonce iiii 9',
        'description': "Description de l'annonce 9 créée pour le compte iiii.",
        'price': 3078.47,
        'category': 'Electronics',
        'type': 'article',
        'image': 'https://placehold.co/600x400?text=Item+9',
        'promo': 10.0,
        'delivery_method': 'delivery',
        'pickup_location': '',
    },
    {
        'user_email': 'ii@g',
        'title': 'Annonce iiii 10',
        'description': "Description de l'annonce 10 créée pour le compte iiii.",
        'price': 7124.44,
        'category': 'Furniture',
        'type': 'service',
        'image': 'https://placehold.co/600x400?text=Item+10',
        'promo': 0,
        'delivery_method': 'pickup',
        'pickup_location': 'Campus central',
    },
]
